### ISSUE TITLE
bigger streampreview is now broken

### ISSUE THREAD

**Issue by ghost** [jaimeadf/BetterDiscordPlugins#410]
incomptabile with the new updates

**Comment by marto05** [comment]
Same. Probably won't get fixed XD

**Comment by Binz1mp** [comment]
@omgs1337 @marto05 

it's kinda too late but for someone who're getting in trouble with this,
you can just add this in custom css:
```css
/* do not change */
div[class*='streamPreview_'] {
  width: 100% !important;
}
/* change height whatever you want */
div[class*='previewContainer_'] {
  height: 500px !important;
}
```
